In [1]:
import pandas as pd 
import statsmodels.formula.api as smf
import statsmodels.api as sm

In [4]:

four_sessions = pd.DataFrame({
    "Page": ["Page 1"] * 5 + ["Page 2"] * 5 + ["Page 3"] * 5 + ["Page 4"] * 5,
    "Time": [
        164, 172, 177, 156, 195,   # Page 1
        178, 191, 182, 185, 177,   # Page 2
        175, 193, 171, 163, 176,   # Page 3
        155, 166, 164, 170, 168    # Page 4
    ]
})

four_sessions

      Page  Time
0   Page 1   164
1   Page 1   172
2   Page 1   177
3   Page 1   156
4   Page 1   195
5   Page 2   178
6   Page 2   191
7   Page 2   182
8   Page 2   185
9   Page 2   177
10  Page 3   175
11  Page 3   193
12  Page 3   171
13  Page 3   163
14  Page 3   176
15  Page 4   155
16  Page 4   166
17  Page 4   164
18  Page 4   170
19  Page 4   168

In [11]:
g = four_sessions.groupby('Page')['Time'].mean()
g  = g.to_frame()
g.T

Page  Page 1  Page 2  Page 3  Page 4
Time   172.8   182.6   175.6   164.6

In [3]:
# observed F from classical ANOVA
model = smf.ols('Time ~ Page', data=four_sessions).fit()
aov_table = sm.stats.anova_lm(model)
aov_table

            df  sum_sq     mean_sq         F    PR(>F)
Page       3.0   831.4  277.133333  2.739825  0.077586
Residual  16.0  1618.4  101.150000       NaN       NaN