# Chi Squared Test

Same as 
```
chisq, pvalue, df, expected = stats.chi2_contingency(table)

In [25]:
import pandas as pd
from scipy import stats

In [12]:
df = pd.DataFrame(
    {
        "Headline A": [14, 986],
        "Headline B": [8, 992],
        "Headline C": [12, 988],
    },
    index=["Click", "No-click"]
)

df

          Headline A  Headline B  Headline C
Click             14           8          12
No-click         986         992         988

In [13]:
# to do a significance test, first create the null world under null hypothesis assumption

row_totals = df.sum(axis=1)
col_totals = df.sum(axis=0)
grand_total = df.values.sum()

In [14]:
expected = pd.DataFrame(
    {
        col: [
            row_totals["Click"] * col_totals[col] / grand_total,
            row_totals["No-click"] * col_totals[col] / grand_total,
        ]
        for col in df.columns
    },
    index=df.index
)

In [15]:
# this is if we assume the null that they're all the same
expected

          Headline A  Headline B  Headline C
Click      11.333333   11.333333   11.333333
No-click  988.666667  988.666667  988.666667

In [16]:
# create table of Pearson Residuals
r = (df - expected)/(expected**0.5)
r

          Headline A  Headline B  Headline C
Click       0.792118   -0.990148    0.198030
No-click   -0.084809    0.106012   -0.021202

In [18]:
# chi-squared stat (X) is the total sum

chi_stat = (r**2).sum().sum()
chi_stat

np.float64(1.6659394708658917)

In [20]:
# degrees of freedom
df_chi = (df.shape[0] - 1) * (df.shape[1] - 1)

In [ ]:
# p value
p_value = 1 - stats.chi2.cdf(chi_stat, df_chi)
p_value

np.float64(0.4347562562343731)

p-value is much greater than 0.05, so strong evidence to support the null. The difference of the click rates of the three headlines is not statistically significant.

In [ ]:
# another test
# null states that voting tendencies is the same for both genders.
votes = pd.DataFrame(
    ((200,150,50),
    (250, 300, 50)),
    columns=['Rep', 'Dem', 'Ind'],
    index=['Male', 'Female']
)

votes

        Rep  Dem  Ind
Male    200  150   50
Female  250  300   50

In [ ]:
chisq, pvalue, df, expected = stats.chi2_contingency(votes)

In [27]:
expected

array([[180., 180.,  40.],
       [270., 270.,  60.]])

In [28]:
chisq, pvalue

(np.float64(16.203703703703702), np.float64(0.0003029775487145488))

The p-value is much less than 0.05, so the probability of these results being by random chance is very low. 

Statistically, we can say that the differences between their results is not by random chance and that we have strong evidence to reject the null.

So voting tendencies do differ by sex, according to the p-value calculated from the samples.